name: test_and_linter

on: push

defaults:
  run:
    working-directory: blog

jobs:
  test_and_linter:
    name: rspec
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: run linter
        run: bundle exec rubocop

      - name: run tests
        run: bundle exec rspec spec
